blueprints/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, DateField
from wtforms.validators import DataRequired, EqualTo


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")


class RegisterForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField("Confirm password", validators=[DataRequired(), EqualTo("password")])
    submit = SubmitField("Register")


class ExpenseForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    value = StringField("Value", validators=[DataRequired()])
    date = DateField("Date", validators=[DataRequired()])
    submit = SubmitField("Add expense")


class ExpenseDateScopeForm(FlaskForm):
    date_start = DateField("Start Date", validators=[DataRequired()], format="%Y-%m-%d")
    date_end = DateField("End Date", validators=[DataRequired()], format="%Y-%m-%d")
    submit = SubmitField("Filter")

app.py
from flask import Flask
from flask_migrate import Migrate
from blueprints.databases import db
from blueprints.main import main, login_manager
from blueprints.expenses import expense


app = Flask(__name__)
app.config.from_pyfile("config.cfg")
app.app_context().push()

db.init_app(app)
login_manager.init_app(app)

migrate = Migrate(app, db)

app.register_blueprint(main)
app.register_blueprint(expense)


with app.app_context():
    db.create_all()

if __name__ == "__main__":
    app.run(debug=True)

blueprints/databases.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    admin = db.Column(db.Boolean, default=False)
    expenses = db.relationship("Expenses", backref="author", lazy=True)


class Expenses(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False)
    value = db.Column(db.Float, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False)

blueprints/expenses.py
from flask import Blueprint, redirect, render_template, url_for, flash, current_app
from flask_login import login_required, current_user
from blueprints.databases import db, Expenses
from blueprints.forms import ExpenseForm, ExpenseDateScopeForm
import matplotlib.pyplot as plt
import os


expense = Blueprint("expense", __name__)


def generate_expense_plot(expenses):
    # Extract data for the plot
    labels = [expense.name for expense in expenses]
    values = [expense.value for expense in expenses]

    # Create the plot
    plt.figure(figsize=(10, 6))
    plt.bar(labels, values, color='skyblue', width=0.4, align='center')
    plt.xlabel('Expense Name')
    plt.ylabel('Expense Value PLN')
    plt.title('Expenses Overview')
    plt.xticks(rotation=45, ha='right')

    # Save the plot to a static folder
    plot_path = os.path.join(current_app.static_folder, 'expense_plot.png')
    plt.tight_layout()
    plt.savefig(plot_path)
    plt.close()  # Close the plot to free memory

    return 'expense_plot.png'


@login_required
@expense.route("/expenses/<int:user_id>", methods=["GET", "POST"])
def expenses(user_id):
    form_date = ExpenseDateScopeForm()
    form = ExpenseForm()

    # Changing date scope to display expenses
    if form_date.validate_on_submit():
        start_date = form_date.date_start.data
        end_date = form_date.date_end.data

        user_expenses = Expenses.query.filter(Expenses.user_id == user_id, Expenses.date_posted >= start_date, Expenses.date_posted <= end_date).order_by(Expenses.date_posted).all()

        expense_plot = generate_expense_plot(user_expenses)
        return render_template(
            "expenses.html",
            user_expenses=user_expenses,
            form=form,
            form_date=form_date,
            expense_plot=expense_plot
        )

    # Default bahaviour
    user_expenses = Expenses.query.filter(Expenses.user_id == user_id).order_by(Expenses.date_posted).all()
    expense_plot = generate_expense_plot(user_expenses)


    return render_template("expenses.html", user_expenses=user_expenses, form=form, form_date=form_date, expense_plot=expense_plot)


@login_required
@expense.route("/add_expense", methods=["GET", "POST"])
def add_expense():
    form = ExpenseForm()

    if form.validate_on_submit():
        name = form.name.data
        value = form.value.data
        date = form.date.data

        new_expense = Expenses(name=name, value=value, date_posted=date, user_id=current_user.id)
        db.session.add(new_expense)
        db.session.commit()

        flash("Expense added!")
        return redirect(url_for("expense.expenses", user_id=current_user.id))
    

@login_required
@expense.route("/delete_expense/<int:expense_id>")
def delete_expense(expense_id):
    expense = Expenses.query.filter(Expenses.id == expense_id).first()

    db.session.delete(expense)
    db.session.commit()
    flash("Expense deleted!")
    return redirect(url_for("expense.expenses", user_id=current_user.id))


@login_required
@expense.route("/edit_expense/<int:expense_id>", methods=["GET", "POST"])
def edit_expense(expense_id):
    expense = Expenses.query.filter(Expenses.id == expense_id).first()
    form = ExpenseForm(obj=expense)

    if form.validate_on_submit():
        expense.name = form.name.data
        expense.value = form.value.data
        expense.date_posted = form.date.data

        db.session.commit()
        flash("Expense edited!")
        return redirect(url_for("expense.expenses", user_id=current_user.id))

    return render_template("edit_expense.html", form=form, expense=expense)

blueprints/main.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user, LoginManager, login_required
from blueprints.forms import LoginForm, RegisterForm
from blueprints.databases import User, db
from werkzeug.security import generate_password_hash, check_password_hash



main = Blueprint("main", __name__)

login_manager = LoginManager()
login_manager.login_view = "main.index"

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@main.route("/", methods=["GET", "POST"])
def index():
    
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            # return to user main page with user data
            return redirect(url_for("expense.expenses", user_id=user.id))
        elif user and not check_password_hash(user.password, form.password.data):
            flash("Incorrect password!")
            return redirect(url_for("main.index"))
        else:
            flash("User not found!")
            return redirect(url_for("main.index"))
        

    return render_template("index.html", form=form)


@login_required
@main.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out!")
    return redirect(url_for("main.index"))


@main.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("expense.expenses", user_id=current_user.id))

    form = RegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data

        user = User.query.filter(User.username == username).first()

        if user:
            flash("Username already exists! Log in now!")
            return redirect(url_for("main.index"))
        else:
            new_user = User(username=username, password=generate_password_hash(password), email=email)
            db.session.add(new_user)
            db.session.commit()
            flash("Successfully registered! You can now log in!")
            return redirect(url_for("main.index"))
    else:
        print(form.errors)


    return render_template("register.html", form=form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expense Tracker</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100..900;1,100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
    
    {% block content %}

    {% endblock %}
    
</body>
</html>

templates/edit_expense.html
{% extends "base.html" %}

{% block content %}

<section class="edit-exp-container">
    <h1 class="title">Edit expense</h1>

    <form action="{{ url_for('expense.edit_expense', expense_id=expense.id) }}" class="edit-expense" method="post">
        {{ form.csrf_token }}

        <div class="new-expense">
            {{ form.name.label }}
            {{ form.name(class_="form-control") }}
        </div>

        <div class="new-expense">
            {{ form.value.label }}
            {{ form.value(class_="form-control") }}
        </div>

        <div class="new-expense">
            {{ form.date.label }}
            {{ form.date(class_="form-control") }}
        </div>

        {{ form.submit(class_="form-btn") }}

    </form>

</section>

{% endblock %}

templates/expenses.html
{% extends "base.html" %}


{% block content %}

<div class="container-main">

    <h1 class="title">Your's expenses</h1>
    <a href="{{ url_for('main.logout') }}" class="btn-reset">Click here to log out!</a>

    <form action="{{ url_for('expense.expenses', user_id=current_user.id) }}" class="date-form" method="post">
        {{ form_date.csrf_token }}

        <div class="form-group">
            {{ form_date.date_start.label }}
            {{ form_date.date_start }}
        </div>

        <div class="form-group">
            {{ form_date.date_end.label }}
            {{ form_date.date_end }}
        </div>

        {{ form_date.submit(class_="date-btn") }}
    </form>

    <a href="{{ url_for('expense.expenses', user_id=current_user.id) }}" class="btn-reset">Reset to Default</a>

    <table class="expense-table">
        <thead>
            <th>Name</th>
            <th>Value</th>
            <th>Date</th>
        </thead>

        <tbody>
            {% for expense in user_expenses %}
                <tr>
                    <td>{{ expense.name }}</td>
                    <td>{{ expense.value }}</td>
                    <td>{{ expense.date_posted.strftime('%Y-%m-%d') }}</td>
                    <td>
                        <a href="{{ url_for('expense.edit_expense', expense_id=expense.id) }}" class="edit-btn table-btn">Edit</a>
                        <a href="{{ url_for('expense.delete_expense', expense_id=expense.id) }}" class="delete-btn table-btn">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- DISPLAY EXPENSE DIAGRAM HERE WITH POSIBILITY FOR CHANGING TIME SCOPE -->
     {% if expense_plot %}
        <img src="{{ url_for('static', filename=expense_plot) }}" alt="Expense Plot" class="expense-chart">
    {% else %}
        <div class="nodata">
            <p>No data avaible</p>
        </div>
    {% endif %}

    <div class="add-expense">

        <h3 class="title">Add new expense</h3>

        <form action="{{ url_for('expense.add_expense') }}" class="expense-form" method="POST">
            {{ form.csrf_token }}

            <div class="new-expense">
                {{ form.name.label }}
                {{ form.name }}
            </div>

            <div class="new-expense">
                {{ form.value.label }}
                {{ form.value }}
            </div>

            <div class="new-expense"">
                {{ form.date.label }}
                {{ form.date }}
            </div>

            {{ form.submit(class_="form-btn") }}

        </form>

    </div>

</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}


{% block content %}

<div class="container">
    <section class="title">
        <h1>Your private expense tracker</h1>
        <p>Track your expenses and manage your budget</p>
        <p>Log in or Register now and start tracking your expenses</p>
    </section>

    <section class="login">
        <h2>Login</h2>
        <form action="{{ url_for('main.index') }}" method="post">
            {{ form.csrf_token }}

            <div class="form-group">
                {{ form.username.label }}
                {{ form.username(class_="form-control") }}
            </div>

            <div class="form-group">
                {{ form.password.label }}
                {{ form.password(class_="form-control") }}
            </div>

            {{ form.submit(class_="form-btn") }}

        </form>
    </section>

    <section class="register-redirect">
        <p>Don't have an account?</p>
        <a class="redirecting" href="{{ url_for('main.register') }}">Register</a>
    </section>
</div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

<section class="container">
    <h1 class="title">Register New user</h1>

    <form action="{{ url_for('main.register') }}" class="reg-form" method="post">
        {{ form.csrf_token }}

        <div class="form-group">
            {{ form.username.label }}
            {{ form.username(class_="form-control") }}
        </div>

        <div class="form-group">
            {{ form.email.label }}
            {{ form.email(class_="form-control") }}
        </div>

        <div class="form-group">
            {{ form.password.label }}
            {{ form.password(class_="form-control") }}
        </div>

        <div class="form-group">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class_="form-control") }}
        </div>

        {{ form.submit(class_="form-btn") }}
    </form>

</section>

{% endblock %}